DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQHRlc3Rlci5jb20iLCJleHAiOjE3MDgwMTczMTMsInVzZXJJZCI6Mn0.LvuHZGeBzbqQpTkxWjnXXNeVtVyyAuHwwxKqIr9N3xc