@host = http://localhost:8080

POST {{host}}/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdGVyLmNvbSIsImV4cCI6MTcwODAxNDI3OSwidXNlcklkIjowfQ.JSgX-eo0J-abbXL02-ZLOUyzbspK7wxHkPRTPNSgNAE

{
    "name": "Test event 2",
    "description": "Another test event",
    "location": "Test location 2",
    "dateTime": "2026-02-01T15:30:00.000Z"
}